Add a test to check mechanism type variants
cryptosense/pkcs11 pull request #106
Opened 2018-10-02 11:50 UTC by leamingrad

This PR enhances `p11_mechanism_type` in a couple of ways:

* Move to using `ppx_variants_conv` to generating the list of all elements of the type. This will cause a compiler warning if new elements are added and omitted from the list
* Add a test that encodes all the variants as a string and then decodes them

2018-10-02 11:51 UTC, leamingrad commented
I'm not a huge fan of `ppx_variants_conv` - in particular, I can't work out if there is a better way to generate the list of variants without duplicating the list.

2018-10-03 18:03 UTC, NathanReb requested changes
Besides that it looks good, I think this test is indeed a nice addition.

Regarding `ppx_variants_conv`, it is as verbose as the hand written list but the compiler will enforce exhaustiveness for us which I don't think can be achieved in a concise way.

I'm a bit torn here, beside that specific use case I don't see much value in it for us, nor do I for most users which would probably just use `elements` if they need to iterate over all variants. I seriously doubt it but is there by any chance a way to only derive this `Variants.fold` function ?
Especially signature wide, having all the first class constructors exposed makes a lot of polution when you're looking through auto-completion suggestions.

2018-10-03 18:03 UTC, NathanReb commented on test/test_p11_mechanism_type.ml
> +      let test expected ctxt =
this function doesn't depend on the `t` parameter so you can probably take it out of the anonymous function. I think that will improve readability.

2018-10-04 07:56 UTC, leamingrad commented on test/test_p11_mechanism_type.ml
> +      let test expected ctxt =
Yeah its nicer now

2018-10-04 08:03 UTC, leamingrad commented
> is there by any chance a way to only derive this `Variants.fold` function ?

I haven't been able to find one. I guess the way to do it would be to extract the relevant pre-processor code from `ppx_variants_conv` and including it in the package. I'm not hugely keen on that as it doesn't seem like a great fit for this codebase.

I think the "correct" solution here would probably be to create a new `ppx_*` package that is a tightened up version of `ppx_variants_conv` that is more tuned to the needs of types that are basically just a load of nullary constructors with a a couple of special cases (or even just for all-nullary classes). Then we can swap that in here. Thats probably something for another time though.

2018-10-04 15:54 UTC, NathanReb approved these changes

2018-10-04 15:55 UTC, NathanReb commented
Agreed, it's already a good improvement as it is!

2018-10-04 15:55 UTC, merged