Use separate integers package and ctypes >= 0.12.0
cryptosense/pkcs11 pull request #54
Opened 2017-05-29 14:26 UTC by bbc2

This brings us closer to a ctypes-independent package, should we need it.

2017-05-29 14:44 UTC, emillon requested changes
Technically we could keep supporting former versions of `ctypes` but I don't think that's worth the hassle. And we already have a quite high version bound for `is_null`, so I think it's OK.

2017-05-29 14:44 UTC, emillon commented on opam
> +  "integers" { >= "0.2.2" }
Do we use any feature introduced in `0.2.2`? Otherwise it's not necessary to add this constraint.

2017-05-29 15:05 UTC, bbc2 commented on opam
> +  "integers" { >= "0.2.2" }
I tried compiling with `0.2.0` and it failed but I haven't looked further.  I'll do that now.

2017-05-30 12:17 UTC, bbc2 commented on opam
> +  "integers" { >= "0.2.2" }
Actually, it works.  I must have forgot to clean the build at some point.

2017-05-30 12:17 UTC, bbc2 commented on opam
> +  "integers" { >= "0.2.2" }
Removed constraint.

2017-06-01 11:37 UTC, bbc2 commented
Anything else that should be fixed?

2017-06-02 09:26 UTC, emillon commented
- the `opam` constraint is superfluous (implied by the bounds on `ctypes`)
-  the `package(integers)` implied by ctypes' `META`
- not sure about `.merlin` but I think it uses findlib, so it's not directly useful either.

This leaves only the version bump on `ctypes`. I don't think this is worth adding while separate compilation is not possible, and it will be easy to add at that point.

2017-06-02 09:42 UTC, bbc2 commented
To all three of your bullet points: As we use the integers package directly, I'd have thought an explicit dependency would be in order.  Don't you think?

2017-06-02 09:58 UTC, emillon commented
OK, that makes sense. We have couple missing dependencies as well: `zarith` comes to mind, but maybe something else pulled through `key-parsers`.

Merging, thanks!

2017-06-02 09:58 UTC, merged